services:
  app:
    build:
      context: .
    entrypoint: ["poetry", "run", "streamlit", "run", "src/app/main.py", "--server.port", "8501"]
    ports:
      - "8501:8501"
  app_ticket_manaer:
    build:
      context: .
    entrypoint: ["poetry", "run", "streamlit", "run", "src/issue-tracker/main.py", "--server.port", "8502"]
    ports:
      - "8502:8502"
  api:
    build:
      context: .
    entrypoint: ["poetry", "run", "uvicorn", "src.api.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    env_file:
      - .env
